// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Dmx.GslCore")>]
[<assembly: AssemblyProductAttribute("Dmx.GslCore")>]
[<assembly: AssemblyDescriptionAttribute("Core library and basic plug-ins for the GSL compiler. (Demetrix production version)")>]
[<assembly: AssemblyVersionAttribute("0.4.34")>]
[<assembly: AssemblyFileVersionAttribute("0.4.34")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Dmx.GslCore"
    let [<Literal>] AssemblyProduct = "Dmx.GslCore"
    let [<Literal>] AssemblyDescription = "Core library and basic plug-ins for the GSL compiler. (Demetrix production version)"
    let [<Literal>] AssemblyVersion = "0.4.34"
    let [<Literal>] AssemblyFileVersion = "0.4.34"
