// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GslCore")>]
[<assembly: AssemblyProductAttribute("GslCore")>]
[<assembly: AssemblyDescriptionAttribute("Core library and basic plug-ins for the GSL compiler.")>]
[<assembly: AssemblyVersionAttribute("0.4.15")>]
[<assembly: AssemblyFileVersionAttribute("0.4.15")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GslCore"
    let [<Literal>] AssemblyProduct = "GslCore"
    let [<Literal>] AssemblyDescription = "Core library and basic plug-ins for the GSL compiler."
    let [<Literal>] AssemblyVersion = "0.4.15"
    let [<Literal>] AssemblyFileVersion = "0.4.15"
