image: mcr.microsoft.com/dotnet/core/sdk:3.1.100-buster


before_script:
  # nuget caching - https://gitlab.com/gitlab-org/gitlab-runner/issues/327
  - export NUGET_PACKAGES=`pwd`/.nuget
  - chmod +x ./build.sh

cache:
  key: global
  paths:
    - .nuget/

stages:
  - build

.build: &build
  stage: build
  script:
    - ./build.sh build

build branch:
  <<: *build
